api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "validation-collection"
type = "function"
uid = "752f0f5d-299e-d552-69f9-5a5f3dced24d31efa299"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.validations.generate.run"
  input_query = "src/cart_validations_generate_run.graphql"
  export = "cart-validations-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
