api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "validation-product"
type = "function"
uid = "58f2e556-71de-9f20-31b8-253ed09179d635b1243e"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.validations.generate.run"
  input_query = "src/cart_validations_generate_run.graphql"
  export = "cart-validations-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
